# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'un7z_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 267)
        self.toolButton_select_un7z_folder = QtWidgets.QToolButton(Form)
        self.toolButton_select_un7z_folder.setGeometry(QtCore.QRect(470, 60, 37, 18))
        self.toolButton_select_un7z_folder.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_select_un7z_folder.setObjectName("toolButton_select_un7z_folder")
        self.label_select_un7z_folder = QtWidgets.QLabel(Form)
        self.label_select_un7z_folder.setGeometry(QtCore.QRect(40, 60, 101, 16))
        self.label_select_un7z_folder.setObjectName("label_select_un7z_folder")
        self.label_input_password = QtWidgets.QLabel(Form)
        self.label_input_password.setGeometry(QtCore.QRect(40, 110, 91, 16))
        self.label_input_password.setObjectName("label_input_password")
        self.lineEdit_input_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_input_password.setGeometry(QtCore.QRect(140, 160, 311, 20))
        self.lineEdit_input_password.setObjectName("lineEdit_input_password")
        self.PushButton_uncompress = QtWidgets.QPushButton(Form)
        self.PushButton_uncompress.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.PushButton_uncompress.setObjectName("PushButton_uncompress")
        self.lineEdit_select_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_select_folder.setGeometry(QtCore.QRect(140, 60, 311, 20))
        self.lineEdit_select_folder.setObjectName("lineEdit_select_folder")
        self.label_input_password_2 = QtWidgets.QLabel(Form)
        self.label_input_password_2.setGeometry(QtCore.QRect(40, 160, 91, 16))
        self.label_input_password_2.setObjectName("label_input_password_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(140, 110, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.PushButton_delete = QtWidgets.QPushButton(Form)
        self.PushButton_delete.setGeometry(QtCore.QRect(250, 210, 81, 31))
        self.PushButton_delete.setObjectName("PushButton_delete")
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setGeometry(QtCore.QRect(360, 210, 81, 31))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "解压助手"))
        self.toolButton_select_un7z_folder.setText(_translate("Form", "..."))
        self.label_select_un7z_folder.setText(_translate("Form", "选择解压文件夹"))
        self.label_input_password.setText(_translate("Form", "选择压缩包类型"))
        self.lineEdit_input_password.setPlaceholderText(_translate("Form", "没有就算了"))
        self.PushButton_uncompress.setText(_translate("Form", "一键解压"))
        self.label_input_password_2.setText(_translate("Form", "输入解压秘密啊"))
        self.comboBox.setItemText(0, _translate("Form", "All"))
        self.comboBox.setItemText(1, _translate("Form", "zip"))
        self.comboBox.setItemText(2, _translate("Form", "7z"))
        self.comboBox.setItemText(3, _translate("Form", "tgz"))
        self.comboBox.setItemText(4, _translate("Form", "gz"))
        self.PushButton_delete.setText(_translate("Form", "删除压缩包"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
